### ISSUE TITLE
Purpose of Calling `done()` on a Promise?

### ISSUE THREAD

**Issue by codediodeio** [twilio/sample-code#83]
Is there a reason `<promise>.done()` is called in this example? It does not exist on a Promise, so this does nothing but throw an error at the end of the chain. 

https://github.com/twilio/sample-code/blob/85e349a0fb0fc2c63c967df61be16439b1d17229/api/v2010/call/create-example-11/create-example-11.3.x.js#L14

**Comment by joliveros** [comment]
Hi @codediodeio,

Thanks for bringing this up. You are correct, however `twilio-node` uses [q](https://github.com/kriskowal/q)
for promises and that does provide the `done()` handler above. In your code, if this is an issue you can just remove that line from the code sample and it should work fine.

Happy coding!
